music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :destroy]
  resources :bands
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    
end

music_app/app/models/user.rb
class User < ApplicationRecord
    validates :email, uniqueness: true, presence: true
    validates :session_token, uniqueness: true, presence: true
    validates :password_digest, presence: true
    validates :password, length: { minimum: 6, allow_nil: true}

    after_initialize :ensure_session_token

    attr_reader :password

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)

        return nil if user.nil?
        user.is_password?(password) ? user : nil
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def reset_session_token!
        self.session_token = SecureRandom.urlsafe_base64
        self.save!
        self.session_token
    end

    private

    def ensure_session_token
        self.session_token ||= SecureRandom.urlsafe_base64
    end

end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token 

    helper_method :current_user, :logged_in?

    private

    def require_no_user!
        redirect_to users_url if current_user
    end

    def current_user
        return nil unless session[:session_token]
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !current_user.nil?
    end

    def login_user!(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout_user!
        current_user.reset_session_token!
        session[:session_token] = nil
    end


end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        # debugger
        user = User.find_by_credentials(
            params[:user][:email],
            params[:user][:password]
        )

        if user.nil?
            flash.now[:errors] = ["Incorrect username and or password"]
            render :new
        else
            login_user!(user)
            redirect_to user_url(user)
        end
    end

    def new
        # debugger
        render :new
    end

    def destroy
        # debugger
        logout_user!
        redirect_to new_session_url
    end

end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
        render :show
    end

    def create
        @user = User.new(user_params)

        if @user.save
            login_user!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def new
        @user = User.new
        render :new
    end

    private

    def user_params
        params.require(:user).permit(:email, :password)
    end

end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <h1> Welcome to MusicApp!!! </h1>

  <div>
    <% if current_user.nil? %>
      <a href="<%= new_session_url %>">Log In</a>
      <br>
      <a href="<%= new_user_url %>">Create an Account</a>
    <% else %>
      <%= current_user.email %>
    <% end %>
  <div>

  <form action="<%= session_url %>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Log Out">
  </form>
  

  <body>
    <%= yield %>
  </body>
</html>

music_app/app/views/users/new.html.erb
<h1>Create a New Account!</h1>

<form action="<%= users_url  %>" method="POST">
    <label for="user_email">Enter Your Email</label>
    <input type="text"
        name="user[email]"
        id="user_email"
        value="">
    <br>

    <label for="user_password">Enter Your Password</label>
    <input type="password"
        name="user[password]"
        id="user_password"
        value="">
    <br>

    <input type="submit" value="Create Account">
</form>

music_app/app/views/users/show.html.erb
<h1>Welcome <%= @user.email %></h1>